export type SupplierResourceDetails = {
    resourceTypeName: string,
    resourceTypeIcon: string,
    resourceId: number,
    resourceName: string,
    supplierId: number,
    supplierName: string,
    lada: string,
    phone: string,
    supplierResourceId: number,
    supplierResourceName: string,
    description: string,
    price: number,
    measureUnit: string,
    mainImage: string,
    images: string[],
}